# Generated by Django 4.0.1 on 2022-02-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cregno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=40)),
                ('cindustry', models.CharField(max_length=40)),
                ('Phone', models.CharField(max_length=10)),
                ('cadd', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=12)),
                ('msg', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cregno', models.CharField(max_length=15)),
                ('openingfor', models.CharField(max_length=30)),
                ('forfresher', models.CharField(max_length=5)),
                ('expinyear', models.IntegerField()),
                ('joblocation', models.CharField(max_length=100)),
                ('ctc', models.CharField(max_length=10)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=10)),
                ('sadd', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=200)),
                ('domainknowledge', models.CharField(max_length=100)),
                ('workexpinyears', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('cpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
