# Generated by Django 4.0.1 on 2022-03-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default=1234, max_length=100),
        ),
    ]
